### ISSUE TITLE
Attention for SH and CG

### ISSUE THREAD

**Issue by smart-chris84** [Jack1993116/Group1-work#19]
For SH and CG, there is no info about bidding on freelancer.
    We need to keep bidding on freelancer. **I want the number of bids spent everyday.**

For SH, we need to reduce the technical debt, that is, keep learning new technologies.
    **I ask SH to come up with a plan of acquiring one new skill this month.**

**Comment by Jack1993116** [comment]
This is SH.
I will make a plan of new skill.
But when we say about bid, I can't focus on the other tasks.
Because as you see, I have 3 tasks now. And this makes me not to focus on other task.
